### ISSUE TITLE
Github Action Permission denied

### ISSUE THREAD

**Issue by Moelf** [kcarloni/PhotosplineReader.jl#3]
https://github.com/kcarloni/PhotosplineReader.jl/actions/runs/7071891577/job/19250101211#step:5:287

>remote: Permission to kcarloni/PhotosplineReader.jl.git denied to github-actions[bot].

to fix this, go to the Setting of repo, and then on the left: `Actions -> General`, then select `Read and Write` under `Workflow permissions`

**Comment by kcarloni** [comment]
Thanks!
