### ISSUE TITLE
Github Pages not build from `gh-pages` branch

### ISSUE THREAD

**Issue by Moelf** [kcarloni/PhotosplineReader.jl#5]
Currently https://kcarloni.github.io/PhotosplineReader.jl/dev is empty.

You want to go to the repo settings -> `Pages` and set the Pages to be deployed from the branch:
![image](https://github.com/kcarloni/PhotosplineReader.jl/assets/5306213/21244752-4a63-49ea-9664-ac471409fa2e)

https://github.com/kcarloni/PhotosplineReader.jl/tree/gh-pages looks okay

**Comment by kcarloni** [comment]
Thanks! :-)
